export default{
	state:{
		tabList:[
			{
				name:'全部',
				list:[
					{
						//地址和下单时间
										
						orderId:'1',//订单号
						orderStatus:'待付款',
						totalPrice:379,
						freight:0.1,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:1,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								}
							}
						],				
						
					},
					{
						orderId:'2',//订单号
						orderStatus:'待发货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								}
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								}
							}
						],				
						
					},
					{
						orderId:'3',//订单号
						orderStatus:'待收货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								}
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								}
							}
						],				
						
					},
					{
						orderId:'4',//订单号
						orderStatus:'待评论',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							}
						],				
						
					}
				]
			},
			{
				name:'待付款',
				list:[
					{
						orderId:'5',//订单号
						orderStatus:'待付款',
						totalPrice:379,
						freight:0.1,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:1,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							}
						],				
						
					},
				],
			},
			{
				name:'待发货',
				list:[
					{
						orderId:'6',//订单号
						orderStatus:'待发货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							}
						],				
						
					},
				],
			},
			{
				name:'待收货',
				list:[
					{
						orderId:'7',//订单号
						orderStatus:'待收货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							}
						],				
						
					},
				],
			},
			{
				name:'待评论',
				list:[
					{
						orderId:'8',//订单号
						orderStatus:'待评论',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						address:{
							userName:'俞用湘',
							tel:'15523990656',
							area:'贵州省 黔南布衣族苗族自治州 都匀市',
							detailAddress:'城东烟酒店2楼',
							tagName:'学校',
							isDefault:false,
						},
						discountPrice:50,
						discountedPrice:49,
						orderTIme:'2023-7-11 11:21:45',
						countdown:24 * 60 * 60 *1000,
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
								coupon:{
									type:'discount',
									name:'生鲜折扣券',
									num:0.55,
									status:'可使用',
									condition:'无门槛使用',
									conditionNum:0,
									validStart:'2019.11.18',
									validEnd:'2023.12.18'
								},
							}
						],				
						
					}
				],
			}
		],	
		tabIndexNow:0,
	},
	getters:{
		
	},
	mutations:{
		updateTabIndexNow(state, index){
			state.tabIndexNow = index
		},
	},
	actions:{
		updateTabIndexNow({commit}, index){
			commit('updateTabIndexNow', index)
		}
	}
}