export default{
	state:{
		tabList:[
			{
				name:'全部',
				list:[
					{
						//折扣和地址和备注
										
						orderId:'12319412313',//订单号
						orderStatus:'待付款',
						totalPrice:379,
						freight:0.1,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:1,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待发货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待收货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待评论',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					}
				]
			},
			{
				name:'待付款',
				list:[
					{
						orderId:'12319412313',//订单号
						orderStatus:'待付款',
						totalPrice:379,
						freight:0.1,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:1,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
				],
			},
			{
				name:'待发货',
				list:[
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待发货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
				],
			},
			{
				name:'待收货',
				list:[
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待收货',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					},
				],
			},
			{
				name:'待评论',
				list:[
					{
						orderId:'3412376587234',//订单号
						orderStatus:'待评论',
						totalPrice:478,
						freight:0.3,
						notes:'这里是备注',
						commodityList:[
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:99.00,
								num:2,
							},
							{
								name:"腾讯极光盒子5智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率",
								commodityStyle:"经典白,经典套装",
								imgUrl:"../../../static/banner/banner1.png",
								price:56.00,
								num:5,
							}
						],				
						
					}
				],
			}
		],	
		tabIndexNow:0,
	},
	getters:{
		
	},
	mutations:{
		updateTabIndexNow(state, index){
			state.tabIndexNow = index
		}
	},
	actions:{
		updateTabIndexNow({commit}, index){
			commit('updateTabIndexNow', index)
		}
	}
}